kind: pipeline
name: default

steps:

- name: build
  image: node
  commands:
  - npm install
  - npm run build

- name: deploy
  image: appleboy/drone-scp
  settings:
    username: andynroses
    host: andynroses.me
    key:
      from_secret: ID_RSA
    target:
        - /home/andynroses/andynroses.me/tracker-man.andynroses.me
    source:
        - ./dist

- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: tracker-man