kind: pipeline
name: default

steps:

- name: build
  image: node
  commands:
  - npm install
  - npm run build

- name: deploy
  image: appleboy/drone-scp
  settings:
    username: 
        from_secret PRODUCTION_USER
    host: 
        from_secret PRODUCTION_HOST
    key:
      from_secret: ID_RSA
    target:
        - /home/andynroses/andynroses.me/tracker-man.andynroses.me
    source:
        - ./dist

- name: slack
  image: plugins/slack
  settings:
    webhook: 
        from_secret SLACK_WEBHOOK
    channel: 
        from_secret SLACK_CHANNEL